"""replace_port_with_url_in_deployments

Revision ID: 14761a650a05
Revises: 64050798e6ef
Create Date: 2026-05-25 10:50:19.813609

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '14761a650a05'
down_revision: Union[str, Sequence[str], None] = '64050798e6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
