"""create_runs_tables

Revision ID: 241c8f211c40
Revises: eb82bb34d2f5
Create Date: 2026-04-12 17:06:50.991792

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '241c8f211c40'
down_revision: Union[str, Sequence[str], None] = 'eb82bb34d2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
