"""add avg_latency_ms to deployments

Revision ID: 582f1882ba52
Revises: d9d87e0a4876
Create Date: 2026-05-16 17:41:46.290926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582f1882ba52'
down_revision: Union[str, Sequence[str], None] = 'd9d87e0a4876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('avg_latency_ms', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'avg_latency_ms')

    # ### end Alembic commands ###
