"""add celery_task_id to runs

Revision ID: c09b70d7fe8b
Revises: ab4e475396d5
Create Date: 2026-04-17 22:54:15.398227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09b70d7fe8b'
down_revision: Union[str, Sequence[str], None] = 'ab4e475396d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('runs', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('f1_score', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('recall', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'runs', ['celery_task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='unique')
    op.drop_column('runs', 'recall')
    op.drop_column('runs', 'precision')
    op.drop_column('runs', 'f1_score')
    op.drop_column('runs', 'accuracy')
    op.drop_column('runs', 'celery_task_id')
    # ### end Alembic commands ###
