"""add models and deployments

Revision ID: c0ca8c7bbd0a
Revises: 55ded011b3f3
Create Date: 2026-04-30 16:21:11.510672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0ca8c7bbd0a'
down_revision = '8fba5ad68f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_environment_id'), 'models', ['environment_id'], unique=False)
    op.create_index(op.f('ix_models_run_id'), 'models', ['run_id'], unique=True)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DEPLOYING', 'ACTIVE', 'STOPPED', 'FAILED', name='deploymentstatus'), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployments_model_id'), 'deployments', ['model_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.drop_table('datasets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('r2_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('env_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['env_id'], ['environments.id'], name=op.f('datasets_env_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('datasets_pkey'))
    )
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_model_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_models_run_id'), table_name='models')
    op.drop_index(op.f('ix_models_environment_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
